language: csharp
solution: screensaver.sln
os: windows
install:
  - nuget restore solution-name.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release screensaver.sln
  - dotnet test