language: csharp
solution: screensaver.sln
install:
  - nuget restore screensaver.sln
  - nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
  - msbuild /p:Configuration=Release screensaver.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.9.0/tools/nunit3-console.exe ./screensaver tests/bin/Release/screensaver tests.dll
