---
name: Tests

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: [windows-latest]
    steps:
      - uses: actions/checkout@v2.1.0
      - name: setup-msbuild
        uses: microsoft/setup-msbuild@v1
      - name: tests
        run: dotnet test
